### ISSUE TITLE
Adjust simulatedData files to new format

### ISSUE THREAD

**Issue by yannikschaelte** [LeonardSchmiester/Benchmark-Models#105]
At least some simulatedData files have not been adjusted to the obervable file introduction -- still have observableTransformation columns. Not sure if some do not apply proper scaling of "simulation"s to linear scale, maybe also worth checking.

**Comment by LeonardSchmiester** [comment]
See issue #96

**Comment by yannikschaelte** [comment]
right. github didn't show me that one :/
