### ISSUE TITLE
obsevableId in Raia shadows model id

### ISSUE THREAD

**Issue by fbergmann** [LeonardSchmiester/Benchmark-Models#108]
the observable file defines id that shadow species ids in the model.

**Comment by fbergmann** [comment]
same for `Korkut_eLIFE2015`

**Comment by LeonardSchmiester** [comment]
Closed by 54fc4f7fb51292577bc914f911513bd8e4087d88 and 5001dd98796075aabf0d0e4d08c479b5cd87b856
