### ISSUE TITLE
Formatting and naming changes

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#11]
- 1 column for observation parameters (observableParameter1;observableParameter2), 1 column for noise parameters (noiseParameter1;noiseParameter2,...), parameters separated by semicolon
- add noise model specification in the SBML add assignment rules for sigma_names
- change observable names to: observable_name

**Comment by LeonardSchmiester** [comment]
- Transpose experimentalCondition table

**Comment by elbaraim** [comment]
*Small remark*
What about switch column "noiseParameters" and "observableTransformation"? So that we have all the information regarding observables together and then the noise parameters.

- Data import robust to text spaces between the observation and noise parameters

**Comment by elbaraim** [comment]
- New __OPTIONAL__ column: Normalization of the exp. data to max. value (see d2d). If the column is not present in the data, that means no normalization.

**Comment by LeonardSchmiester** [comment]
- rename first column in measurementData from observable to observableName

**Comment by dweindl** [comment]
> * rename first column in measurementData from observable to observableName

Maybe rather `observableId`? This is more in line with the SBML Id/Name terminology

**Comment by LoosC** [comment]
decided on observableID

**Comment by dweindl** [comment]
> decided on observableID

`Id` would be slightly more readable when appended to

**Comment by LoosC** [comment]
Then we should also use conditionId instead of conditionID in the other file

**Comment by dweindl** [comment]
> Then we should also use conditionId instead of conditionID in the other file 

Absolutely.

**Comment by LeonardSchmiester** [comment]
simulationConditionId and preequilibrationConditionId

**Comment by LeonardSchmiester** [comment]
- for the simulatedData sheet, write the estimated values of the observableParameters and noiseParameters in the respective columns

**Comment by dweindl** [comment]
I guess there was more that changed and is now documented in https://github.com/ICB-DCM/PEtab . Close?
