### ISSUE TITLE
Parameter bounds

### ISSUE THREAD

**Issue by yannikschaelte** [LeonardSchmiester/Benchmark-Models#12]
Currently, parameter bounds are only specified in the general_info file. do we keep that one? it might be good to have the lower and upper bounds on parameters in a separate file. suggest a simple tsv file w/ 3 columns (parameter_id, lower_bound, upper_bound).

**Comment by LeonardSchmiester** [comment]
I would add an additional column for parameter scale

**Comment by LeonardSchmiester** [comment]
We decided on a format for this. See Boehm model for an example

**Comment by yannikschaelte** [comment]
We decided to have the values and bounds in the scaled space, e.g. loc-space, right? Would make sense to specify this in the documentation.MD.

**Comment by yannikschaelte** [comment]
Done and parameter list specification given in the documentation file now. Must be done for all models.
