### ISSUE TITLE
Add standard format for simulation and optimization options

### ISSUE THREAD

**Issue by LeonardSchmiester** [LeonardSchmiester/Benchmark-Models#13]

**Comment by LeonardSchmiester** [comment]
Do we still want to have this?

**Comment by paulstapor** [comment]
I thiink we agreed on some point that a yaml-ish file might be a good start here. But I think this is rather low prio...

**Comment by yannikschaelte** [comment]
yes, we/I started using yaml for that. it is medium prio when it comes to parallelization

**Comment by LeonardSchmiester** [comment]
yaml files exist now. Issue can be closed
