### ISSUE TITLE
new format for Fiedler

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#16]

**Comment by yannikschaelte** [comment]
When doing analysis in pypesto, a first challenge is that there are replicates (in the form of multiple observable parameters for the same condition and observable). this can be solved by adding a second condition for each of data1,2,3.
However, then I still get an objective at the nominal parameters of 1.08e8, which is much too high.

**Comment by yannikschaelte** [comment]
Observable scales are linear, that's fine. Could someone look into this from the model side, whether everything is correct?

**Comment by dweindl** [comment]
Model parameter 'sigma_pErk' is target of AssignmentRule, and thus, must not be present in condition table or in parameter table.

**Comment by LoosC** [comment]
Its not present in the condition table, but its a parameter which is estimated and thus listed in the parameter table, right?

**Comment by dweindl** [comment]
`sigma_pErk` is reserved for specifying the noise model. The parameter which is to be used cannot have the same name. That is sometimes unfortunate, but it is what we currently require in PEtab. So the `sigma_pErk` in the measurement table needs to be changed to something else.
