### ISSUE TITLE
new format for Zheng

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#17]

**Comment by yannikschaelte** [comment]
Question: The model is supposed to have 48 parameters, thereof 1 noise parameter. However, in the sbml file, there are number_of_observables_many, giving a total of 60 parameters. Should there maybe be only 1 noise_... parameter which is mapped to all sigma_... parameters?

**Comment by LoosC** [comment]
as far as I understood, the mapping is only done with the measurementData sheet. So in the SBML we might have much more parameters - one for each observable - than estimated. Maybe @LeonardSchmiester can confirm?
