### ISSUE TITLE
new format for weber

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#2]

**Comment by yannikschaelte** [comment]
I think there is in the model the assignment rule for observableParameter1_PI4K3Bt missing (maybe also others).

**Comment by LoosC** [comment]
commit e415f4a7b2905fb78b54e94e35ae75b16034f95b wrongly assinged to #27

**Comment by yannikschaelte** [comment]
std_ parameters for the noise parameters are missing in parameters file, but exist in measurement file

**Comment by LoosC** [comment]
to continue on this issue, I need to check why its not included in the d2d export of models. I currently have problems in reproducing the d2d output and asked @elbaraim to check whether the problem also exists for her.

**Comment by LoosC** [comment]
@elbaraim what is the state of this?

**Comment by LoosC** [comment]
d2d export for benchmark models did not extract noise parameters to general_info file

**Comment by LeonardSchmiester** [comment]
What's the status here @elbaraim, @LoosC ?

**Comment by LeonardSchmiester** [comment]
Manually added the noise parameters now
