### ISSUE TITLE
new format for Elowitz

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#24]

**Comment by LoosC** [comment]
simulatedData sheet needs to be filled

**Comment by dweindl** [comment]
offset_fluorescence missing in parameter table

**Comment by yannikschaelte** [comment]
same probably for scaling_fluorescence and sd_fluorescence. However, there exist suspicious scale and sigma parameters in the parameter tsv

**Comment by fbergmann** [comment]
as mentioned during the hackathon, we can only correctly simulate this model, if we transform the measurement values. in discussions at the hackathon, it became clear that this should not happen. In which case the measurement data seems off. I'll make a pull request with the transformed data.
