### ISSUE TITLE
new format for Schwen

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#28]

**Comment by elbaraim** [comment]
simulatedData sheet needs to be filled

**Comment by yannikschaelte** [comment]
Schwen has no experimentalCondition file.

**Comment by yannikschaelte** [comment]
The parameters offset_IR, scale_IR, sd_IR, sd_Insulin seem to appear in the measurement file, but not in the parameters file? Maybe these are offset, scale, sd?

**Comment by elbaraim** [comment]
Parameter file was generated by Philipp, may be good to ask him.

May be useful to run `generate_parameter_sheet.py` ?

**Comment by LeonardSchmiester** [comment]
Philipp used the parameters in the parameters sheet from `general_info`. There these parameters don't exist. 
I would guess, Yannik is right, and `offset`, `scale` and `sd` where renamed adding `_IR`. Did you rename them @elbaraim?

**Comment by yannikschaelte** [comment]
I think sd_Insulin is also missing, so it's not only renaming
