### ISSUE TITLE
observable transformation encoded in SBML

### ISSUE THREAD

**Issue by elbaraim** [LeonardSchmiester/Benchmark-Models#31]
log10 or log transformations of the observables are at the moment encoded in the SBML.
this also appears in the measurement data file

**Comment by JanHasenauer** [comment]
For the models I transformed, I removed the log and log10 from the SBML and indicated it in the data sheet.

I would suggest that we do this for all models.

**Comment by JanHasenauer** [comment]
I checked all models and romped the log transformation of the observables if it was specified in the data sheet. Only for Hass I left it untouched as the xml file is not valid SBML.
