### ISSUE TITLE
new format for Hass

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#35]

**Comment by elbaraim** [comment]
sigma parameters are missing in the SBML file
not named as "sd_" -> "sigma_"

**Comment by elbaraim** [comment]
in the observable tApoER2
change observableParameter2_tApo -> observableParameter2_tApoER2

**Comment by dweindl** [comment]
`Reelin_input` in condition table but not in model

**Comment by LeonardSchmiester** [comment]
Reelin_input is fixed. Inh is still missing in the reactions. Inh is already replaced by 0/1 in the SBML models at multiple positions in the reactions. Might take a while to fix that.
