### ISSUE TITLE
Noise parameter documentation

### ISSUE THREAD

**Issue by yannikschaelte** [LeonardSchmiester/Benchmark-Models#36]
Document how the noise parameter construct is meant (this lead to some problems in the import and seems to be handled not fully coherently in the converted models ...).
+ What exactly is the concept behind the sigma_... and noise_... parameters in the sbml file (again :) )?
+ How to handle condition-specific noise parameters / models?
+ What is supposed to be filled in the noiseParameters column in the measurement file unless specified as a float?

**Comment by LoosC** [comment]
will add a description in the documentation, but short answer here:
>     * What exactly is the concept behind the sigma_... and noise_... parameters in the sbml file (again :) )?
- sigma_observableId specifies the full noise model, could for example also be something like: sigma_observableId = noiseParameter1_observableId + noiseParameter2_observableId * observable_observableId, but usually we have just a simple noise model with sigma_observableId = noiseParameter1_observableId 
>     * How to handle condition-specific noise parameters / models?
- which conditions/observables/... share noise parameters is be defined in the measurementData sheet 
>     * What is supposed to be filled in the noiseParameters column in the measurement file unless specified as a float?
- sorry I do not understand the question? in this column we have the string for the noise parameter

**Comment by yannikschaelte** [comment]
Thanks for clarifying. Concerning question 1: That's what I guessed. So in the Zheng model, should that one ``noise`` parameter be mapped to all ``noiseParameter1_observableId`` parameters? I.e. we have a mapping rule ``${noise} -> ${noise}Parameter1_${observableId}$ \forall ${observableId}?

Concerning question 3: By noise parameter you mean the sigma parameter in the wording of the sbml file? Or noise=sigma?

Ok, let's maybe discuss tomorrow. Probably I'm just confused.  :)

**Comment by LoosC** [comment]
> Thanks for clarifying. Concerning question 1: That's what I guessed. So in the Zheng model, should that one noise parameter be mapped to all noiseParameter1_observableId parameters? I.e. we have a mapping rule ``${noise} -> ${noise}Parameter1_${observableId}$ \forall ${observableId}?

yes exactly

> Concerning question 3: By noise parameter you mean the sigma parameter in the wording of the sbml file? Or noise=sigma?

I mean the noiseParameter in the wording of the SBML file but yes lets discuss tomorrow :)

**Comment by yannikschaelte** [comment]
resolved.
