### ISSUE TITLE
Rounded parameter values in parameters_*.tsv 

### ISSUE THREAD

**Issue by dweindl** [LeonardSchmiester/Benchmark-Models#37]
When transferring parameter values from `General_info.xlsx` to `parameters_*.tsv`, they got rounded quite harshly to 2 digits after the comma. Was that on purpose?

**Comment by yannikschaelte** [comment]
Maybe we want to also upload scripts used for automatic model conversion (so far I guess there exist ones for simulated data, measured data, and parameter extraction)? So we can track such issues easily. And it makes it easier for other people to add models.

**Comment by LoosC** [comment]
no the values should be not rounded
