### ISSUE TITLE
change column estimated -> estimate

### ISSUE THREAD

**Issue by LoosC** [LeonardSchmiester/Benchmark-Models#41]
to make it clearer that its not an estimated value in that column we decided to change the column name to estimate

**Comment by yannikschaelte** [comment]
just saying that I just had a look at the ``estimate`` column and thought at the first moment that "estimate" was a noun, i.e. that the column contains the estimated value :).

**Comment by JanHasenauer** [comment]
hm, TRUE / FALSE instead of 1 / 0 ?
