### ISSUE TITLE
Model features to consider for setting up pypesto import

### ISSUE THREAD

**Issue by dweindl** [LeonardSchmiester/Benchmark-Models#47]
**Beer_MolBioSystems2014** 
- using `piecewise`

**Brannmark_JBC2010** 
- using `piecewise`

**Isensee_JCB2018** 
- using `piecewise`

**Bruno_JExpBio2016** 
- parameter names in condition table

**Fiedler_BMC2016**
- timepoint-specific observableParameters

**Swameye_PNAS2003**
- events

**Weber_BMC2015**
- numeric observable overrides

**Comment by JanHasenauer** [comment]
The piecewise command is used in several models to implement steps. Is there another way which is already supported by (py)AMICI?

**Comment by dweindl** [comment]
> The piecewise command is used in several models to implement steps. Is there another way which is already supported by (py)AMICI?

As far as I know, there isn't

**Comment by dweindl** [comment]
In matlab AMICI, piecewise works, for python see https://github.com/ICB-DCM/AMICI/issues/615.

Model peculiarites now listed in table in the model directory. Closing.
