### ISSUE TITLE
Remove old files from benchmark repo and history

### ISSUE THREAD

**Issue by yannikschaelte** [LeonardSchmiester/Benchmark-Models#63]
There are a lot of old files (from d2d export?) that are not needed for the new petab format, totalling to >400MB. Since downloading that is cumbersome, can we get rid of that old stuff maybe?

**Comment by dweindl** [comment]
Not so trivial on github. That pretty much means creating a new repository. Would do that along with merging changes back to upstream. There we should then have one model/data-only repository, and separate repos for any analyses.

**Comment by LeonardSchmiester** [comment]
New clean repository created now
