### ISSUE TITLE
Additional model: Alkan_DDRP_SciSignal2018

### ISSUE THREAD

**Issue by erikadudki** [LeonardSchmiester/Benchmark-Models#72]
a new model in the d2d-examples exist 
https://github.com/Data2Dynamics/d2d/tree/master/arFramework3/Examples/Alkan_DDRP_SciSignal2018
maybe adding to the Benchmark-collection?

**Comment by LaraFuhrmann** [comment]
Corrected input parameters

**Comment by dweindl** [comment]
What's the reason for the NaN measurements included here? https://github.com/LeonardSchmiester/Benchmark-Models/blob/hackathon/hackathon_contributions_new_data_format/Alkan_SciSignal2018/measurementData_Alkan_SciSignal2018.tsv#L488

**Comment by LeonardSchmiester** [comment]
```
Missing parameter(s) in parameter table: {'Wip1_mRNA_fold', 'yH2AX_au', 'pATM_au', 'tp53_au', 'pDNAPK_au', 'pChk1_au', 'tp21_au', 'pChk2_au', 'p21_mRNA_fold', 'pp53_au'}
Not OK
```
Seems like for every observable, there exists a parameter `observable_ID` and a parameter `ID`
@LaraFuhrmann: Can you take care of this?

**Comment by LaraFuhrmann** [comment]
> ```
> Missing parameter(s) in parameter table: {'Wip1_mRNA_fold', 'yH2AX_au', 'pATM_au', 'tp53_au', 'pDNAPK_au', 'pChk1_au', 'tp21_au', 'pChk2_au', 'p21_mRNA_fold', 'pp53_au'}
> Not OK
> ```
> 
> Seems like for every observable, there exists a parameter `observable_ID` and a parameter `ID`
> @LaraFuhrmann: Can you take care of this?

I deleted the parameters with only ID inn the SBML, since they were not used. Now there are only parameters observable_ID.

**Comment by LeonardSchmiester** [comment]
Thank you! Import works fine now :+1:
