### ISSUE TITLE
Where to host benchmark repository?

### ISSUE THREAD

**Issue by LeonardSchmiester** [LeonardSchmiester/Benchmark-Models#73]
We discussed, that we want to host this repository somewhere else. I would suggest the benchmark-initiative project (https://github.com/Benchmarking-Initiative), if that is possible.

I guess it would be good to create a clean project there to get rid of the old matlab files (related to issue #63) and copy the issues from here to the new repository.

Any opinions?

**Comment by paulstapor** [comment]
No need to track the Matlab files in the history, that's just unnecessary storage.
If necessary due to the last publication, I would suggest plugging the initial commit on zenodo, if this isn't done automatically anyways...
Then we're definitely safe to prune out Matlab from the history...

**Comment by dweindl** [comment]
Strongly in favor of having this at https://github.com/Benchmarking-Initiative.

As the publication promises matlab code and analyses at https://github.com/Benchmarking-Initiative/Benchmark-Models, maybe it would be good to put them in a Benchmark-Models-V2 repository there, which is a bit more lightweight. The README could include a link to the new repo.

Should be discussed with current owners/maintainers.

**Comment by paulstapor** [comment]
Alternatively: Benchmark-models-PEtab might be a good name

**Comment by LeonardSchmiester** [comment]
Sounds good. Then we should discuss with Clemens if he can give us owner rights there.

**Comment by dweindl** [comment]
> Sounds good. Then we should discuss with Clemens if he can give us owner rights there.

First project for https://www.integrative-pathway-models.de/meetings/income2019-conference-and-hackathon/index.html ?
