### ISSUE TITLE
Schwen_PONE2014 measurements are in log scale, but should be lin

### ISSUE THREAD

**Issue by dweindl** [LeonardSchmiester/Benchmark-Models#85]
... (the measurements should be adapted, not the observableTransformation) as recently clarified in PEtab.

At least that is what i assume from the negative values there.

**Comment by dweindl** [comment]
Same for Bachmann_MSB2011, Hass, Lucarelli, Sobotta

**Comment by LeonardSchmiester** [comment]
Should be fixed by 776d73775beadf930cd651c0f0d3cee357089f2b
