### ISSUE TITLE
issue with measurement data in Bruno_JExpBio2016

### ISSUE THREAD

**Issue by fbergmann** [LeonardSchmiester/Benchmark-Models#95]
the newly added data sets `model1_data3` and `model1_data6` seem to be in the wrong scale.

**Comment by LeonardSchmiester** [comment]
What do you mean exactly? Measurement values are all positive and as far as I can see it, there were no newly added datasets in the measurement file

**Comment by fbergmann** [comment]
All simulations in that model are in the range of 0..4 the data in data3 and data6 are however in the range of 0...2800 ... so they don't match. this happened in commit 

dda334ad97fd8a15abcb8f79fb4dd3410dfc98ff

**Comment by LeonardSchmiester** [comment]
Ah true. Apparently, the `.` got lost on the way there. Thank you for pointing that out.
@LaraFuhrmann I think you have to change your decimal seperator settings. Can you revert the changes and also check for other models, that you worked on.

**Comment by LeonardSchmiester** [comment]
Same issue for swameye at the moment

**Comment by LeonardSchmiester** [comment]
Swameye and Bruno are fixed now.
