### ISSUE TITLE
Fix observableIds shadowing species IDs

### ISSUE THREAD

**Issue by dweindl** [LeonardSchmiester/Benchmark-Models#98]
Fix observable IDs shadowing IDs of species or other SBML entities

see https://github.com/PEtab-dev/PEtab/issues/292#issue-564832327

also affects:

- [x] Schwen_PONE2014
- [x] Zheng_PNAS2012

**Comment by LeonardSchmiester** [comment]
Schwen, Zhen, Parmar and Bachmann have unique observable Ids now

**Comment by yannikschaelte** [comment]
should all be fine now
